development:
  secret_key_base: super_long_secret_key_for_development
  google_client_id: 879217564228-5g4kno9hpljueqd24pmaq24g4pcd2f6d.apps.googleusercontent.com
  google_client_secret: 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
